load("//tools/build_rules:module_rules.bzl", "buck_module")

buck_module(
  name = "mozilla",
  srcs = glob(["*.java"]),
  provided_deps = [
    "//src/com/facebook/buck/event:interfaces",
    "//src/com/facebook/buck/features/zip/rules:rules",
    "//src/com/facebook/buck/features/filebundler:filebundler",
    "//src/com/facebook/buck/io:io",
    "//src/com/facebook/buck/rules/keys:keys",
    "//src/com/facebook/buck/model:model",
    "//src/com/facebook/buck/module:module",
    "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
    "//src/com/facebook/buck/core/rules:rules",
    "//src/com/facebook/buck/core/sourcepath/resolver/impl:impl",
    "//src/com/facebook/buck/rules/modern:modern",
    "//src/com/facebook/buck/step:step",
    "//src/com/facebook/buck/step/fs:fs",
    "//src/com/facebook/buck/util:util",
    "//src/com/facebook/buck/util/zip:zip",
    "//src/com/facebook/buck/versions:versions",
    "//src/com/facebook/buck/zip:zip",
  ],
)
