load("//tools/build_rules:module_rules.bzl", "buck_module")

buck_module(
  name = 'javascript',
  srcs = glob(['*.java']),
  provided_deps = [
    "//src/com/facebook/buck/config:config",
    "//src/com/facebook/buck/graph:graph",
    "//src/com/facebook/buck/io:io",
    "//src/com/facebook/buck/model:model",
    "//src/com/facebook/buck/core/description/arg:arg",
    "//src/com/facebook/buck/core/description/attr:attr",
    "//src/com/facebook/buck/core/model/targetgraph:targetgraph",
    "//src/com/facebook/buck/core/rules:rules",
    "//src/com/facebook/buck/core/rules/tool:tool",
    "//src/com/facebook/buck/core/toolchain/tool:tool",
    "//src/com/facebook/buck/core/toolchain/tool/impl:impl",
    "//src/com/facebook/buck/shell:steps",
    "//src/com/facebook/buck/step:step",
    "//src/com/facebook/buck/step/fs:fs",
    "//src/com/facebook/buck/versions:versions",
    "//src/com/facebook/buck/util:exceptions",
    "//src/com/facebook/buck/util:util",
    "//third-party/java/jackson:jackson-core",
    "//third-party/java/jackson:jackson-databind",
  ],
  visibility = [
    "//src/com/facebook/buck/core/rules:types",
  ],
)
